### ISSUE TITLE
Personal Access Token is expiring

### ISSUE THREAD

**Issue by sumanthratna** [HackTJ/status#10]
urgent, the fine-grained PAT (that allows `upptime-bot` to commit to the repo) is expiring in 6 days. @krishnans2006 and co, re-make the PAT per Upptime docs

**Comment by krishnans2006** [comment]
Done, as of a few months ago (see [here](https://github.com/organizations/HackTJ/settings/personal-access-tokens/active)). Thanks for the reminder!
